default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rtj_back_dev

test:
  <<: *default
  database: rtj_back_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
